
;
USE ONLOOKER
;
CREATE TABLE UserLogin
(ID INT PRIMARY KEY IDENTITY,
Login VARCHAR(15) NOT NULL,
Password VARCHAR(8) NOT NULL)
;
CREATE TABLE UserInfo
(ID INT PRIMARY KEY IDENTITY,
Name NVARCHAR(15) NOT NULL,
Email VARCHAR(50) UNIQUE NOT NULL,
LoginID INT)
;
CREATE TABLE Country
(ID INT PRIMARY KEY IDENTITY,
Code VARCHAR(10),
Name VARCHAR(20))
;
CREATE TABLE Tag
(ID INT PRIMARY KEY IDENTITY,
Name VARCHAR(50));
CREATE TABLE CurrencyType
(ID INT PRIMARY KEY IDENTITY,
CurrencyCode VARCHAR(3),
CurrencyName VARCHAR(20))
;
CREATE TABLE CurrencyPair
(ID INT PRIMARY KEY IDENTITY,
BaseCurrencyID INT,
QuotedCurrencyID INT,
CONSTRAINT FK_CurrencyBase_CurrencyPair FOREIGN KEY (BaseCurrencyID)
REFERENCES CurrencyType (ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_CurrencyQuoted_CurrencyPair FOREIGN KEY (QuotedCurrencyID)
REFERENCES CurrencyType (ID) 
ON DELETE NO ACTION
ON UPDATE NO ACTION)
;
CREATE TABLE Job
(ID INT PRIMARY KEY IDENTITY,
CurrencyPairID INT NOT NULL,
CountryID INT NOT NULL,
TagID INT NOT NULL,
CONSTRAINT FK_Job_CurrencyPair FOREIGN KEY (CurrencyPairID)
REFERENCES CurrencyPair (ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_Job_Country FOREIGN KEY (CountryID)
REFERENCES Country
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_Job_Tag FOREIGN KEY (TagID)
REFERENCES Tag
ON DELETE CASCADE
ON UPDATE CASCADE)
;
CREATE TABLE UserJobs
(ID INT PRIMARY KEY IDENTITY,
UserID INT NOT NULL,
JobID INT NOT NULL,
CONSTRAINT FK_UserInfo_Job FOREIGN KEY (UserID)
REFERENCES UserInfo(ID) 
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_Job_UserInfo FOREIGN KEY (JobID)
REFERENCES Job (ID)
ON DELETE CASCADE
ON UPDATE CASCADE)
;
CREATE TABLE Article
(ID INT PRIMARY KEY IDENTITY,
URL VARCHAR(100),
Title NVARCHAR(256),
Content NVARCHAR(max),
HTML VARBINARY(max),
Date DATETIME,
CountryID INT
CONSTRAINT FK_Country_Article FOREIGN KEY (CountryID)
REFERENCES Country (ID)
ON DELETE CASCADE
ON UPDATE CASCADE)
;
CREATE TABLE ArticleTag
(ID INT PRIMARY KEY IDENTITY,
ArticleID INT NOT NULL,
TagID INT NOT NULL,
CONSTRAINT FK_Article_Tag FOREIGN KEY (ArticleID)
REFERENCES Article(ID) 
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_Tag_Article FOREIGN KEY (TagID)
REFERENCES Tag (ID)
ON DELETE CASCADE
ON UPDATE CASCADE)
;
CREATE TABLE Report
(ID INT PRIMARY KEY IDENTITY,
JobID INT NOT NULL,
CONSTRAINT FK_Report_Job FOREIGN KEY (JobID)
REFERENCES Job (ID) 
ON DELETE CASCADE
ON UPDATE CASCADE)
;
CREATE TABLE CurrencyPairTimePrint
(ID INT PRIMARY KEY IDENTITY,
Bid DECIMAL NOT NULL,
Ask DECIMAL NOT NULL,
DateTime DATE,
CurrencyPairID INT NOT NULL,
CONSTRAINT FK_CurrencyPair_TimePrINT FOREIGN KEY (CurrencyPairID)
REFERENCES CurrencyPair(ID) 
ON DELETE CASCADE
ON UPDATE CASCADE)
;
CREATE TABLE ReportCurPairTimePrints
(ID INT PRIMARY KEY IDENTITY,
CurPairTimePrintID INT NOT NULL,
ReportID INT NOT NULL,
CONSTRAINT FK_CPTimePrnt_Report FOREIGN KEY (CurPairTimePrintID)
REFERENCES CurrencyPairTimePrint(ID) 
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT FK_Report_CPTimePrnt FOREIGN KEY (ReportID)
REFERENCES Report (ID)
ON DELETE CASCADE ON UPDATE CASCADE)
;
CREATE TABLE MigrationHistory
(ID INT PRIMARY KEY IDENTITY,
MajorVersion VARCHAR(2),
MinorVersion VARCHAR(2),
FileNumber VARCHAR(4),
Comment VARCHAR(255),
DateApplied DATETIME)
;
CREATE TABLE Logs
(ID INT PRIMARY KEY IDENTITY,
LogLevel VARCHAR(20),
Message VARCHAR(200),
CreatedOn DATE)
;
